[package]
name = "hypermon"
version = "0.1.0"
authors = ["Adam <sector-f@users.noreply.github.com>"]

[dependencies]
serde = "1.0.71"
serde_derive = "1.0.71"
serde_json = "1.0.24"
virt = "0.2.8"
clap = "2.32.0"
